name = "day05"
description = ""
version = "0.1.0-dev"

authors = ["Derek Kingston"]
maintainers = ["Derek Kingston <derek.kingston@gmail.com>"]
maintainers-logins = ["derekkingston"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["day05"]
